#!/bin/bash

set -euo pipefail

function frint() {
    mode=$1
    shift
    case "$mode" in
        i)
        color=94;;
        w)
        color=93;;
        e)
        color=91;;
        *)
        frint e "invalid frint mode: $mode"
        exit 1;;
    esac

    printf '[\e[1;%sm%s\e[0m]\e[1;%sm %s\e[0m\n' "$color" "$mode" "$color" "$*"
}

function valid() {
    if [ -v "$1" ]; then
        name="$1"
        shift
        if [ -z "${!name}" ]; then
            frint e "Variable '$name' is empty."
            frint i "Check the configuration file."
        fi
        is_valid=1
        for i in "$@"; do
            if [ "$i" = "${!name}" ]; then
                is_valid=0
                break
            fi
        done
        return $is_valid
    else
        frint e "Variable '$1' does not exist."
        frint i "Check the configuration file."
        exit 1
    fi
}

# TODO selectively load variables from file instead
function store() {
    if [ -v "${1}" ]; then
        declare -g "STORE_${1}=${!1}"
        unset "$1"
    fi
}

function restore() {
    varname="STORE_${1}"
    if [ -v "${varname}" ]; then
        declare -g "$1"="${!varname}"
    fi
    unset "$varname"
    unset varname
}

if [ ! -v 1 ]; then
    frint e 'No target executable supplied.'
    exit 1
fi

if [ ! -e "$1" ]; then
    frint e 'Target executable does not exist.'
    exit 1
fi

if [ -d "$1" ]; then
    frint e "$1 is a folder."
    exit 1
fi

FILE="$1"
FOLDER="$(dirname "$FILE")"

if [ ! -v CONF ]; then
    for confile in {"$FOLDER","$HOME"{,/.config}}/{,.}proton.conf; do
        if [ -e "$confile" ]; then
            frint i "Using: $confile"
            CONF="$confile"
            break
        fi
    done

    if [ ! -v CONF ]; then
        frint i "Creating new proton config: ./proton.conf"
        cat > ./proton.conf << EOF
#!/bin/bash

# Proton version string (eg. GE-Proton10-25-physx)
VERSION="Proton 7.0"
# Proton host paths (to add another add a PROTONDIR variable and increment the number at the end)
PROTONDIR0="$HOME/.steam/root/compatibilitytools.d/"
PROTONDIR1="$HOME/.steam/root/steamapps/common/"
# Proton compatibility client directory
COMPAT_CLIENT_DIR="$HOME/.proton/comp"
# Proton prefix, if Default, the ProtonCompatibility dir will be created next to the executable run with proton
COMPATDIR=Default
# Working Directory, if empty the working dir will be the path of the executable run with proton
WORKINGDIR=
# 0: Disabled, 1: Enabled, 2: OpenGL
MANGOHUD=0
# Enable Feral GameMode
GAMEMODE=0
# Enable DirectX to Vulkan translation over WineD3D
DXVK=1
ESYNC=1
# 0: Disabled, 1: Enabled, 2: Disable Futex2
FSYNC=1
D3D11=1
D3D10=1
EOF
        CONF="./proton.conf"
    fi
fi

store VERSION
store COMPATDIR
store WORKINGDIR
store MANGOHUD
store GAMEMODE
store DXVK
store ESYNC
store FSYNC
store D3D10
store D3D11

source "$CONF"

valid MANGOHUD 0 1 2
valid GAMEMODE 0 1
valid DXVK 0 1
valid ESYNC 0 1
valid FSYNC 0 1 2
valid D3D10 0 1
valid D3D11 0 1

restore VERSION
restore COMPATDIR
restore WORKINGDIR
restore MANGOHUD
restore GAMEMODE
restore DXVK
restore ESYNC
restore FSYNC
restore D3D10
restore D3D11

if [ "$DXVK" = "1" ]; then frint i "Using DXVK"; else frint i "Using WineD3D"; fi
if [ "$MANGOHUD" = "1" ]; then frint i "Using MangoHud"; fi
if [ "$MANGOHUD" = "2" ]; then frint i "Using MangoHud (OpenGL)"; fi
if [ "$GAMEMODE" = "1" ]; then frint i "Enabling Feral GameMode"; fi
if [ "$ESYNC" = "1" ]; then frint i "Enabling Esync"; fi
if [ "$FSYNC" = "1" ]; then frint i "Enabling Fsync"; fi
if [ "$FSYNC" = "2" ]; then frint i "Enabling Futex2"; fi
if [ "$D3D10" = "1" ]; then frint i "Disabling Direct3D 10"; fi
if [ "$D3D11" = "1" ]; then frint i "Enabling Direct3D 11"; fi
if [ "$COMPATDIR" = "Default" ]; then
    frint i "Using default compat dir $FOLDER/ProtonCompatibility"
    mkdir -p "$FOLDER/ProtonCompatibility"
    COMPATDIR="$FOLDER/ProtonCompatibility"
else frint i "Using compat dir $COMPATDIR"; fi
frint i "Using proton version $VERSION"

if [ -z "$WORKINGDIR" ]; then
    frint i "Using Working Directory $FOLDER"
    cd "$FOLDER"
else
	if [ -e "$WORKINGDIR" ]; then
		frint i "Using Working Directory $WORKINGDIR"
		cd "$WORKINGDIR"
	else
		frint e "Working Directory does not exist."
		exit
	fi
fi

PROTON_PATH=
c=0
while true; do
    num=$c
#     if [ "$num" -eq 1 ]; then
#         num=
#     fi
    varname="PROTONDIR${num}"
    if [ -v "$varname" ]; then
        if [ -e "${!varname}/$VERSION/proton" ]; then
            frint i "Found proton $VERSION at path ${!varname}"
            PROTON_PATH="$(readlink -f "${!varname}/$VERSION/proton")"
            echo $PROTON_PATH
            break
        fi
    else
        break
    fi
    c=$(($c + 1))
done
unset c

if [ -z "$PROTON_PATH" ]; then
    frint e "Could not find proton '$VERSION'"
    frint e "Double check your proton dirs in the config file"
#     frint w remember to uncomment this exit here
    exit
fi

USE_GAMEMODE=
USE_MANGOHUD=

if [ "$DXVK" = 0 ]; then
    export PROTON_USE_WINED3D='1'
fi
if [ "$D3D10" = 0 ]; then
    export PROTON_NO_D3D10='1'
fi
if [ "$D3D11" = 0 ]; then
    export PROTON_NO_D3D11='1'
fi
case "$FSYNC" in
    0)
        export PROTON_NO_FSYNC='1'
        ;;
    2)
        export WINEFSYNC_FUTEX2='0'
        ;;
esac
if [ "$ESYNC" = 0 ]; then
    export PROTON_NO_ESYNC='1'
fi
if [ "$GAMEMODE" = 1 ]; then
    USE_GAMEMODE='gamemoderun'
fi
case "$MANGOHUD" in
    1)
        USE_MANGOHUD='mangohud'
        ;;
    2)
        USE_MANGOHUD='mangohud --dlsym'
        ;;
esac

export STEAM_COMPAT_DATA_PATH="$(readlink -f "$COMPATDIR")"
export STEAM_COMPAT_CLIENT_INSTALL_PATH="$(readlink -f "$COMPAT_CLIENT_DIR")"

$USE_GAMEMODE $USE_MANGOHUD "$PROTON_PATH" run "$@"
